name: Vintage Computer Club Malta
favicon: null
layout_spectrum: 0.4345
typography_spectrum: 1
title: Vintage Computer Club Malta (VCCM)
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#335599'
    - '#99aa99'
    - '#7f7f99'
    - '#0f0f3f'
  brandStrength: 0.125
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
