name: Vintage Computer Club Malta
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Vintage Computer Club Malta (VCCM)
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000066'
    - '#336699'
    - '#999999'
    - '#cccccc'
    - '#2f2f66'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
